services:

  ###################################
  ## Exportação de GDB para CSV
  ###################################
  gdb-export--redis:
    image: redis
    networks:
      - gdb-export--network
    profiles:
      - gdb-export

  gdb-export--gdb2csv:
    build:
      context: jobs/gdb2csv
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - gdb-export--volume:/data:rw
    networks:
      - gdb-export--network
    profiles:
      - gdb-export

  gdb-export--fastapi:
    build:
      context: jobs/api
      dockerfile: dockerfile
    environment:
      REDIS_SERVER: redis://gdb-export--redis:6379
      C_FORCE_ROOT: "true"
      INFISICAL_ADDRESS: ${INFISICAL_ADDRESS}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      GDB_EXPORT_USERNAME: ${GDB_EXPORT_USERNAME}
      GDB_EXPORT_PW_HASH: ${GDB_EXPORT_PW_HASH}
    ports:
      - "5000:5000"
    depends_on:
      - gdb-export--redis
    restart: on-failure:5
    volumes:
      - gdb-export--volume:/data:rw
    networks:
      - gdb-export--network
    profiles:
      - gdb-export

  gdb-export--celery_worker:
    build:
      context: jobs/celery
      dockerfile: dockerfile
    environment:
      ENVIRONMENT: dev
      REDIS_SERVER: redis://gdb-export--redis:6379
      EXPORT_SERVER: http://gdb-export--gdb2csv:3000
      C_FORCE_ROOT: "true"
      INFISICAL_ADDRESS: ${INFISICAL_ADDRESS}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
    depends_on:
      - gdb-export--redis
    # Em caso de erro, tenta reiniciar até 5x; isso evita
    # restarts infinitos em caso de credenciais faltantes
    restart: on-failure:5
    volumes:
      - gdb-export--volume:/data:rw
    networks:
      - gdb-export--network
    profiles:
      - gdb-export

  gdb-export--flower:
    image: mher/flower
    command: ["celery", "--broker=redis://gdb-export--redis:6379", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - gdb-export--redis
    restart: on-failure:5
    networks:
      - gdb-export--network
    profiles:
      - gdb-export

  ###################################


volumes:
  gdb-export--volume:

networks:
  gdb-export--network:
    driver: bridge
