# HTTP -> HTTPS
server {
    listen 80;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    http2 on;

    # FIXME
    ssl_certificate /etc/.../fullchain.pem;
    ssl_certificate_key /etc/.../privkey.pem;

    location / {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;

        # HSTS, força HTTPS
        add_header Strict-Transport-Security "max-age=5184000; includeSubDomains" always;
        # Bloqueia uso em <iframe>
        add_header X-Frame-Options "DENY" always;
        # Piadoca
        add_header X-Powered-By "pizza" always;
    }
}
