name: Deploy All Cloud Run Jobs

# FIXME: O job de deploy precisa ser modificado, porque estamos
# usando Docker Compose agora

# on:
#   push:
#     branches:
#       - main

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Discover and deploy all jobs
        run: |
          for dir in jobs/*/ ; do
            JOB_NAME=$(basename "$dir")
            IMAGE_NAME="gcr.io/$PROJECT_ID/$JOB_NAME"

            echo "Building and pushing image for $JOB_NAME"
            docker build -t $IMAGE_NAME "$dir" .
            gcloud auth configure-docker --quiet
            docker push $IMAGE_NAME

            echo "Deploying Cloud Run job: $JOB_NAME"
            gcloud run jobs deploy "$JOB_NAME" \
              --image="$IMAGE_NAME" \
              --region="$REGION" \
              --command="python3" \
              --args="main.py" \
              --set-env-vars="ENVIRONMENT=prod" \
              --max-retries=1 \
              --memory=1024Mi \
              --cpu=1 \
              --timeout=2000
          done
